name: Tinfoil Private Inference Build Action
description: Builds, attests, and publishes a private inference deployment.

author: Tinfoil

inputs:
  config-file:
    description: "Path to the Tinfoil config file"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  prerelease:
    description: "Whether to mark the GitHub release as a prerelease"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0

    - name: Ensure gh CLI supports attestation (>= 2.67.0)
      shell: bash
      run: |
        GH_VERSION=$(gh --version | head -1 | awk '{print $3}')
        MIN_VERSION="2.67.0"
        echo "gh version: $GH_VERSION (minimum: $MIN_VERSION)"
        
        if [ "$(printf '%s\n' "$MIN_VERSION" "$GH_VERSION" | sort -V | head -1)" != "$MIN_VERSION" ]; then
          echo "ERROR: gh CLI version $GH_VERSION is too old. Need >= $MIN_VERSION for attestation support."
          exit 1
        fi

    - name: Create deployment manifest
      shell: bash
      run: |
        docker run --rm \
          -v $(pwd)/output:/output \
          -v ${{ inputs.config-file }}:/config.yml \
          -e GH_TOKEN=${{ inputs.github-token }} \
        ghcr.io/tinfoilsh/pri-build-action@sha256:1757ead035a9181ccbe6ad23731bf06d96ff2fdc70e7254e12be5b5a0051edd8

    - name: Fix output permissions
      shell: bash
      run: sudo chown -R $(id -u):$(id -g) output

    - name: Hash deployment manifest
      shell: bash
      id: hash
      run: |
        echo stdout=sha256:$(sha256sum output/tinfoil-deployment.json | cut -d ' ' -f 1 | tee output/tinfoil.hash) >> $GITHUB_OUTPUT

    - name: Attest
      uses: actions/attest@7667f588f2f73a90cea6c7ac70e78266c4f76616 #v3.1.0
      id: attest
      with:
        subject-name: tinfoil-deployment.json
        subject-digest: ${{ steps.hash.outputs.stdout }}
        predicate-type: https://tinfoil.sh/predicate/snp-tdx-multiplatform/v1
        predicate-path: output/tinfoil-deployment.json

    - name: Generate release notes
      shell: bash
      run: |
        cat output/release.md > output/release-notes.md
        echo "" >> output/release-notes.md
        echo "Digest: \`$(cat output/tinfoil.hash)\`" >> output/release-notes.md
        echo "Sigstore Link: https://search.sigstore.dev/?hash=$(cat output/tinfoil.hash)" >> output/release-notes.md

    - name: Create release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        PRERELEASE_FLAG=""
        if [ "${{ inputs.prerelease }}" = "true" ]; then
          PRERELEASE_FLAG="--prerelease"
        fi
        
        gh release create "${{ github.ref_name }}" \
          -R ${{ github.repository }} \
          --title "${{ github.ref_name }}" \
          --notes-file output/release-notes.md \
          $PRERELEASE_FLAG \
          output/tinfoil-deployment.json \
          output/tinfoil.hash
